### ISSUE TITLE
QQ消息中的@未转义，转发时展示成[cq:at,qq=xxxxxx]

### ISSUE THREAD

**Issue by infnan** [infnan/LilyWhiteBot#12]

**Comment by Zokhoi** [comment]
應該有兩個問題

1. `plugins/transport/processors/QQ.js`代碼89行`qqHandler.getNick(info)`不知道為啥執行不了，我試過加一行`console.log(qqHandler.getNick(info))`運行時沒有顯示


2. 既然前面context.text已經轉義了為啥又要從rawdata再轉義一次啊。

**Comment by infnan** [comment]
这块代码有点坑，`.catch(_ => {})`，其实里头已经产生异常，只是不打日志的话看不出来
